export const CATEGORY_ACTIONS = {
  FETCH_CATEGORY_START: 'category/FETCH_CATEGORY_START',
  FETCH_CATEGORY_SUCCESS: 'category/FETCH_CATEGORY_SUCCESS',
  FETCH_CATEGORY_FAIL: 'category/FETCH_CATEGORY_FAIL',
};
